
    public enum ObjectsInLevel { 
        Null,
        BennyTwospoons, 
        AyTheTearCollector, 
        Sentinel, 
        Gorilla,
        ArmadilloCostume, 
        Lute, 
        CashMachine, 
        ClownNoses,
        SneezePowder,
        TwoSpoonsPainting1,
        TwoSpoonsPainting2,
        TwoSpoonsPainting3,
        TwoSpoonsWallPainting,
        Wigs,
        Hatch,
        Marionet,
        ClownCertificate,
        LapelFlowers,
        ExplodingCandles,
        RockingHorse,

        TheTwoSpoonsSign,
        BeehiveHut,
        Carrot,
        TearCollectorSkull,
        TreasureChest,

        CaveSign,

        MuseumDoor,
        ApathyHead,
        MuseumLeftPanel,
        MuseumMiddlePanelLeft,
        MuseumMiddlePanelMiddle,
        MuseumMiddlePanelRight,
        MuseumRightPanel,
        MuseumRightPanelTower,
        MuseumRightPanelCynicism,
        MuseumRightPanelCrater,
        MuseumRightPanelOffering,
        SideDoor,
        DamagedWall,
        MaskOfMockery,

        Wheel1,
        Wheel2,
        Wheel3,
        Wheel4,
        Wheel5,
        Wheel6,

        Rabbit,
    };
